name: Bug Report
description: Report a bug or issue with Arlo Meeting Assistant
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Example: The live transcript stops updating after 10 minutes..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Start a Zoom meeting
        2. Open Arlo Meeting Assistant
        3. Click "Start RTMS"
        4. Wait 10 minutes
        5. Notice transcript stops updating
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The transcript should continue updating in real-time throughout the entire meeting."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "The transcript stopped updating after 10 minutes, but the meeting continued."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Backend API
        - Frontend (Zoom App)
        - RTMS Ingestion
        - Database
        - AI Features
        - Docker Setup
        - Documentation
        - Not Sure
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node Version: [e.g., 20.10.0]
        - Docker Version: [e.g., 24.0.6]
        - Zoom Client Version: [e.g., 5.17.0]
        - Browser (if applicable): [e.g., Chrome 120]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant log output (use `docker-compose logs backend` or similar)
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the troubleshooting guide in the documentation
          required: true
        - label: I am using the latest version of the code
          required: false
