name: Question or Help
description: Ask a question or get help with Arlo Meeting Assistant
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please fill out the form below and we'll do our best to help.

        **Note:** For general discussion, consider using [GitHub Discussions](../../discussions) instead.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "Example: How do I configure the AI model to use a different provider?"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Setup and Installation
        - Zoom App Configuration
        - RTMS Integration
        - AI Features
        - Database and Migrations
        - Docker and Deployment
        - API Usage
        - Development and Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        Example:
        - Checked the documentation
        - Searched existing issues
        - Tried restarting Docker containers
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Tell us about your environment
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node Version: [e.g., 20.10.0]
        - Docker Version: [e.g., 24.0.6]
        - Zoom Client Version: [e.g., 5.17.0]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots that might help.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
